export const ImagesPath = {
  appStoreLogo:
    "https://res.cloudinary.com/dlinffsds/image/upload/v1678826278/apple-icon_vsksjl.svg",
  playStoreLogo:
    "https://res.cloudinary.com/dlinffsds/image/upload/v1678828252/google_play_vtcizu.svg",
  heroImage:
    "https://res.cloudinary.com/getabacus/image/upload/v1678983413/app/web/hero-mockup_he2kso.svg",
  rightRoadMapLine:
    "https://res.cloudinary.com/dlinffsds/image/upload/v1678823317/map-line-right_od2rbc.svg",
  leftRoadMapLine:
    "https://res.cloudinary.com/dlinffsds/image/upload/v1678824945/map-line-left_m3wesj.svg",
  carbonIcon:
    "https://res.cloudinary.com/dlinffsds/image/upload/v1678825127/carbon-icon_hdplxf.svg",
  fcmbIcon:
    "https://res.cloudinary.com/dlinffsds/image/upload/v1678878837/fcmb-icon_elrb7l.svg",
  kudaIcon:
    "https://res.cloudinary.com/getabacus/image/upload/v1679042665/app/web/bamboo-icon_kgfmoc.svg",
  abegIcon:
    "https://res.cloudinary.com/dlinffsds/image/upload/v1678825943/abeg-icon_o28wdp.svg",
  startIcon:
    "https://res.cloudinary.com/dlinffsds/image/upload/v1678861483/Star_1_geekvj.svg",
  pocketMockup:
    "https://res.cloudinary.com/dlinffsds/image/upload/v1678866557/Group_2079_fzzkh2.svg",
  faqImage:
    "https://res.cloudinary.com/dlinffsds/image/upload/v1678873935/Frame_325_ulnvij.svg",
  accountsMockup:
    "https://res.cloudinary.com/getabacus/image/upload/h_900/web/mockup.png",
  dashIcon:
    "https://res.cloudinary.com/getabacus/image/upload/v1678935089/app/web/Expand_Arrow_kcgdqu.svg",
  arrowDownIcon:
    "https://res.cloudinary.com/getabacus/image/upload/v1678935207/app/web/Horizontal_Line_g6jpxq.svg",
  menuIcon:
    "https://res.cloudinary.com/getabacus/image/upload/v1678971394/app/web/menu-button_zqfl30.svg",
  twitterIcon:
    "https://res.cloudinary.com/getabacus/image/upload/v1678973385/app/web/twitter-icon_2_tu5rls.svg",
  walletMockup:
    "https://res.cloudinary.com/getabacus/image/upload/v1678984412/app/web/wallet-mockup_xzznue.svg",
  securityImage:
    "https://res.cloudinary.com/getabacus/image/upload/v1678991995/app/web/cyborg-key-3_1_vapdxs.svg",
  closeIcon:
    "https://res.cloudinary.com/getabacus/image/upload/v1679030683/app/web/Vector_hnbrxw.svg",
};

export const SocialMediaIcons = {
  instagram:
    "https://res.cloudinary.com/dlinffsds/image/upload/v1678887094/instagram-icon_pewvcl.svg",
  twitter:
    "https://res.cloudinary.com/getabacus/image/upload/v1678973385/app/web/twitter-icon_2_tu5rls.svg",
  telegram:
    "https://res.cloudinary.com/getabacus/image/upload/v1678973490/app/web/Frame_251_ajutlh.svg",
  linkedInIcon:
    "https://res.cloudinary.com/getabacus/image/upload/v1678973546/app/web/Frame_250_vkkib7.svg",
  facebook:
    "https://res.cloudinary.com/getabacus/image/upload/v1678973600/app/web/Frame_250_1_uvkgcg.svg",
};
