/* eslint-disable @next/next/no-img-element */
import type { NextPage } from "next";
import Head from "next/head";
import styles from "./chat/chat.module.css";

const Home: NextPage = () => {
  const infos = [
    {
      title: "Interpretation and Definitions\n\nInterpretation",
      description:
        "The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.",
    },
    {
      title: "Definitions",
      description: "For the purposes of this Privacy Policy:",
      lists: [
        "Account means a unique account created for You to access our Service or parts of our Service.",
        'Affiliate means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.',
        "Application means the software program provided by the Company downloaded by You on any electronic device, named Abacus.",
        'Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Abacus Tecnologies Studio Inc.',
        "Cookies are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.",
        "Country refers to: California, United States",
        "Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.",
        "Personal Data is any information that relates to an identified or identifiable individual.",
        "Service refers to the Application or the Website or both.",
        "Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.",
        "Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).",
        "Website refers to Abacus, accessible from www.getabacus.app",
        "“You” means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.",
      ],
    },
    {
      title:
        "Collecting and Using Your Personal Data\n\nTypes of Data Collected\n\nPersonal Data",
      description:
        "While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:",
      lists: [
        "Email address",
        "First name and last name",
        "Phone number",
        "Address, State, Province, ZIP/Postal code, City",
      ],
    },
    {
      title: "Usage Data",
      description:
        "Usage Data is collected automatically when using the Service.\n\nUsage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.\n\nWhen You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.\n\nWe may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.",
    },
    {
      title: "Information Collected while Using the Application",
      description:
        "While using Our Application, in order to provide features of Our Application, We may collect, with Your prior permission:",
      lists: [
        "Information regarding your location",
        "Information about the use of the product",
      ],
      footer:
        "We use this information to provide features of Our Service, to improve and customize Our Service. The information may be uploaded to the Company's servers and/or a Service Provider's server or it may be simply stored on Your device.\n\nYou can enable or disable access to this information at any time, through Your Device settings.",
    },
    {
      title: "Tracking Technologies and Cookies",
      description:
        "We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:",
      lists: [
        "Cookies or Browser Cookies. A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.",
        "Flash Cookies. Certain features of our Service may use local stored objects (or Flash Cookies) to collect and store information about Your preferences or Your activity on our Service. Flash Cookies are not managed by the same browser settings as those used for Browser Cookies.",
        "Web Beacons. Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).",
      ],
      footer:
        'Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser. You can learn more about cookies here: All About Cookies by TermsFeed.',
    },
    {
      title: "Use of Your Personal Data",
      description:
        "The Company may use Personal Data for the following purposes:",
      lists: [
        "To provide and maintain our Service, including to monitor the usage of our Service.",
        "To make available to You services, products, applications or skills provided by third parties. We share any of Your personal information related to the third party transaction carried out with Our Service.",
        "To manage Your Account: to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.",
        "For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.",
        "To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.",
        "To provide You with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.",
        "To manage Your requests: To attend and manage Your requests to Us.",
        "For business transfers: We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.",
        "For other purposes: We may use Your information for other purposes, such as data analysis, protecting Our Company, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.",
      ],
      footer: "",
    },
    {
      title: "",
      description:
        "We may share Your personal information in the following situations:",
      lists: [
        "With Service Providers: We may share Your personal information with Service Providers to monitor and analyze the use of our Service and provide services to us.",
        "Financial Data Sources: We may share information with the Financial Data Sources to help establish or maintain an integration you have chosen to make.",
        "For business transfers: We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.",
        "With Affiliates: We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.",
        "With business partners: We may share Your information with Our business partners to offer You certain products, services or promotions.",
        "With other users: when you share personal information or otherwise interact in public areas with other users, such information may be viewed by all users and may be publicly distributed outside.",
        "With Your consent: We may disclose Your personal information for any other purpose with Your consent.",
      ],
    },

    {
      title: "Retention of Your Personal Data",
      description:
        "The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.\n\nThe Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.",
    },
    {
      title: "Transfer of Your Personal Data",
      description:
        "Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.\n\nYour consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.\n\nThe Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.",
    },

    {
      title: "Disclosure of Your Personal Data",
      description:
        "Business Transactions\n\nIf the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.\n\nLaw Enforcement\n\nUnder certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).\n\nOther Legal Requirements\n\nThe Company may disclose Your Personal Data in the good faith belief that such action is necessary to:",
      lists: [
        "Comply with a legal obligation",
        "Protect and defend the rights or property of the Company",
        "Prevent or investigate possible wrongdoing in connection with the Service",
        "Protect the personal safety of Users of the Service or the public",
        "Protect against legal liability",
      ],
      footer:
        "Security of Your Personal Data\n\nThe security of Your Personal Data is important to Us and We work hard to protect the security of Your Personal Information during transmission using encryption protocols and software, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.\n\nIt is also important for You to protect against unauthorised access to Your password and to your devices and applications. We recommend using a unique password for Abacus that is not used for other online accounts.",
    },
    {
      title: "Children's Privacy",
      description:
        "Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We will take steps to remove that information from Our servers.\n\nIf We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.",
    },
    {
      title: "Links to Other Websites",
      description:
        "Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.\n\nWe have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.",
    },

    {
      title: "Changes to this Privacy Policy",
      description:
        'We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.\n\nWe will let You know by updating the "Last updated" date at the top of this Privacy Policy. You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.',
    },

    {
      title: "Contact Us",
      description: `If you have any questions about this Privacy Policy, You can contact us by email: support@trustabacus.com`,
    },
  ];

  return (
    <>
      <div>
        <Head>
          <title>Abacus - Manage your money</title>
          <meta name="description" content="Misson control for your money" />
          <link rel="icon" href="/image/favicon.ico" />
        </Head>

        <div className={styles["maw-xl"]}>
          <h1 className="mb">Privacy policy</h1>

          <p className="mb">Effective Date: September 1, 2022</p>

          <p>
            This Privacy Policy describes Our policies and procedures on the
            collection, use, and disclosure of Your information when You use the
            Service and tells You about Your privacy rights and how the law
            protects You. {<br />}We use Your Personal data to provide and
            improve the Service. By using the Service, You agree to the
            collection and use of information in accordance with this Privacy
            Policy.
          </p>

          {infos.map((info, index) => {
            return (
              <div key={index.toString()} className="mb-l">
                {info.title ? (
                  <h2 className="pt-l mb-l mt-l">{info.title}</h2>
                ) : null}
                {info.description ? (
                  <div className="mb">
                    <p className="mb">{info.description}</p>
                  </div>
                ) : null}
                {info.lists && info.lists.length > 0
                  ? info.lists.map((listItem, index) => {
                      return (
                        <div
                          className="mb-s flex-center-y"
                          style={{ marginLeft: "1rem" }}
                          key={index}
                        >
                          <div style={{ marginRight: "1.25rem" }}>
                            <p>•</p>
                          </div>
                          {listItem ? (
                            <div>
                              <p className="mb">{listItem}</p>
                            </div>
                          ) : null}
                        </div>
                      );
                    })
                  : null}
                {info.footer && info.footer.length > 0 ? (
                  <div className="mb">
                    <p>{info.footer}</p>
                  </div>
                ) : null}
              </div>
            );
          })}
        </div>
      </div>
    </>
  );
};

export default Home;
